apiVersion: apps/v1
kind: Deployment
metadata:
  name: devprodb
  labels:
    app: devprodb
spec:
  selector:
    matchLabels:
      app: devprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: devprodb
    spec:
      containers:
      - name: devprodb
        image: memoor/devprodb:V1
        args:
        - "--ignore-db-dir=lost+found"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: devpro-db-data
        ports:
        - name: devprodb-port
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-pass
      nodeSelector:
        zone: us-east-2a
      volumes:
      - name: devpro-db-data
        # This AWS EBS volume must already exist.
        awsElasticBlockStore:
          volumeID: vol-0ce1beeac1c7df574
          fsType: ext4
